---
kind: "operation"
client: "atomist-bot"
generator:
  name: "NewRestService"
  group: "satellite-of-love"
  artifact: "rest-service-generator"
  version: "0.11.9"
  origin:
    repo: "git@github.com:satellite-of-love/rest-service-generator"
    branch: "restrict-cors"
    sha: "e241a51"
  parameters:
    - "description": "moar kitties"

